[workspace]
resolver = "2"
members = [
    "bins/hnt-agent",
    "bins/hnt-chat",
    "bins/hnt-edit",
    "bins/hnt-llm",
    "bins/hnt-web",
    "bins/hnt-tui",
    "bins/headlesh",
    "crates/hinata-core",
]
